const data= {
    products:[
        {
            _id:'1',
            name:'Home use bench',
            category:'Benches',
            image:'./images/bench.jpg',
            price:'10,000',
            countInStock:100,
            brand: 'Wilad Sports House',
            rating:5,
            numReviews:10,
            description:'high quality bench',
        },
        {
            _id:'2',
            name:'Barbell',
            category:'Bars',
            image:'./images/Barbell.jpg',
            price:'5000', countInStock:100,
            brand: 'Wilad Sports House',
            rating:5,
            numReviews:10,
            description:'high quality barbell',
        },
        {
            _id:'3',
            name:'EZ bar',
            category:'Bars',
            image:'./images/EZ bar.jpg',
            price:'5000', countInStock:100,
            brand: 'Wilad Sports House',
            rating:5,
            numReviews:10,
            description:'high quality bar',
        },
        {
            _id:'4',
            name:'Dumbell rods',
            category:'Dumbell',
            image:'./images/dumbell rods.jpg',
            price:'3000', countInStock:100,
            brand: 'Wilad Sports House',
            rating:5,
            numReviews:10,
            description:'high quality dumbell',
        },
        {
            _id:'5',
            name:'Full cage',
            category:'Power rack',
            image:'./images/full cage.jpg',
            price:'50000', countInStock:100,
            brand: 'Wilad Sports House',
            rating:4,
            numReviews:10,
            description:'high quality rack',
        },
        {
            _id:'6',
            name:'Sit up bench',
            category:'Benches',
            image:'./images/sit-up bench.jpg',
            price:'10,000', countInStock:100,
            brand: 'Wilad Sports House',
            rating:4.5,
            numReviews:10,
            description:'high quality bench',
        },
        {
            _id:'7',
            name:'incline bench',
            category:'Benches',
            image:'./images/incline bench.jpg',
            price:'10,000', countInStock:100,
            brand:'Wilad Sports House',
            rating:4.5,
            numReviews:10,
            description:'High quality bench',
        },
        {
            _id:'8',
            name:'latpulldown1',
            category:'Latpulldown',
            image:'./images/latpulldown1.jpg',
            price:'50,000', countInStock:100,
            brand:'Wilad Sports House',
            rating:4.5,
            numReviews:10,
            description:'High quality bench',
        },
        {
            _id:'9',
            name:'Latpulldown2',
            category:'Latpulldown',
            image:'./images/Latpulldown2.jpg',
            price:'50,000', countInStock:100,
            brand:'Wilad Sports House',
            rating:4.5,
            numReviews:10,
            description:'High quality Latpulldown',
        },
        {
            _id:'10',
            name:'latpulldown3.jpg',
            category:'Latpulldown',
            image:'./images/latpulldown3.jpg',
            price:'50,000', countInStock:100,
            brand:'Wilad Sports House',
            rating:4.0,
            numReviews:48,
            description:'High quality Latpulldown',
                    
        },
        {
            _id:'11',
            name:'latpulldown4.jpg',
            category:'Latpulldown',
            image:'./images/latpulldown4.jpg',
            price:'70,000', countInStock:100,
            brand:'Wilad Sports House',
            rating:4.0,
            numReviews:70,
            description:'High quality Latpulldown',
                
        },
        {
            _id:'12',
            name:'Legpress',
            category:'Legpress',
            image:'./images/legpress1.jpg',
            price:'90,000', countInStock:100,
            brand:'Wilad Sports House',
            rating:4.5,
            numReviews:67,
            description:'High quality legpress'
        },
    ]
}
export default data;